name: gerris-ci

on:
  pull_request:
  push:
    branches:
      - master

env:
  RUSTFLAGS: '-Dwarnings'

jobs:
  coding-style:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check the coding style
      run: cargo fmt -- --check

  check:
    runs-on: ubuntu-latest
    needs: coding-style

    steps:
    - uses: actions/checkout@v2
    - name: Run check
      run: cargo check
    - name: Run Clippy
      run: cargo clippy --all -- -Wclippy::pedantic
    - name: Run tests
      run: cargo test

  docker-build-check:
    runs-on: ubuntu-latest
    needs: check

    steps:
      - uses: actions/checkout@v2
      - name: Check the project's docker image is functional
        run: |
          docker build . -t gerris-tmp
